Added dummy glXCreateWindow/glXDestroyWindow stubs
Just like glXCreateGLXPixmap/glXDestroyGLXPixmap they don't do
anything useful (and hence are not really correct). Still they are
needed for compiling supertuxkart 0.8 and avoid linking problems:

    undefined reference to `glXCreateWindow'
    undefined reference to `glXDestroyWindow'